#include<iostream>
#include<vector>
#include<algorithm>

int main()
{
	std::vector<int> ivec; //empty vector
	fill_n(back_inserter(ivec), 10, 1);
	for(std::vector<int>::iterator iter = ivec.begin() ; iter != ivec.end() ; ++iter)
	{
		std::cout<<*iter<<std::endl;
	}
	/*
	 * Now, each time fill_n writes a value, it will do so through the insert iterator generated by
	 * back_inserter. The effect will be to call push_back on ivec, adding ten elements to the end of ivec,
	 * each of which has the value 1*/
	return 0;
}
